name: My sample Pipeline

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2 

      - name: Welcome message
        run: echo "My sample pipeline creation" >> mysample.txt

      - name: List files
        run: ls
      - name: Reading file
        run: cat mysample.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: sample-txt
          path: mysample.txt 

  second_jobs:
    runs-on: ubuntu-22.04
    needs: first_job
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: sample-txt

      - name: Listing the file in the repo
        run: ls -ltr

      - name: REading the downloaded artifact
        run: cat mysample.txt          

            
 